---
title: "Model2_ROI_analysis_ZG"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

Load packages
```{r libraries, results = "hide", message = FALSE, warning = FALSE}
library(tidyverse)
library(readxl)
library(ggpmisc)
library(Matrix)
library(lmerTest)
require(cowplot)
library(gridExtra)
library(ggbeeswarm)
library(reshape2)
library(performance)
library(ggeffects)
require("gridExtra")
library(latex2exp)
library(stringr)
library(ggtext)
library(writexl)
library(grid)
library(rlang)
library(purrr)
library(ggpubr)

```

Importing the linear regression results
```{r}
MWF_results <- read_excel("Table_S6.xlsx", sheet = 'TableS6_WHIIRS_MWF')
R1_results <- read_excel("Table_S6.xlsx", sheet = 'TableS6_WHIIRS_R1')
R2_results <- read_excel("Table_S6.xlsx", sheet = 'TableS6_WHIIRS_R2')
FA_results <- read_excel("Table_S6.xlsx", sheet = 'TableS6_WHIIRS_FA')
AxD_results <- read_excel("Table_S6.xlsx", sheet = 'TableS6_WHIIRS_AxD')
RD_results <- read_excel("Table_S6.xlsx", sheet = 'TableS6_WHIIRS_RD')
MD_results <- read_excel("Table_S6.xlsx", sheet = 'TableS6_WHIIRS_MD')
```


Making the table of all the values together for the heatmap
```{r}
parameters <- c("Main Effect", "Sex Interaction", "Female", "Male")
MRI_metrics <- c("MWF", "R1", "R2", "FA", "AxD", "MD", "RD")
ROIs <- MWF_results$ROI

chart_df <- data.frame(parameter = character(), ROI = character(), modality = character(), p_value = numeric(), fdr_val = numeric(), coefficient = numeric(), stringsAsFactors = FALSE)

for (metric in MRI_metrics){ # goes through every metric (MWF, R1, etc)
  for (roi in ROIs){ # goes through every ROI

      beta <- as.numeric(get(paste0(metric, "_results"))[which(get(paste0(metric, "_results"))$ROI == roi), "beta logWHIIRS"])
      fdr <- as.numeric(get(paste0(metric, "_results"))[which(get(paste0(metric, "_results"))$ROI == roi), "fdr_sig logWHIIRS"])
      
      if (metric == "AxD" | metric == "MD" | metric == "RD"){ # this is to make the trend about the amount of myelin, NOT about the raw values
        beta = -beta
      }

      # Store results
      chart_df <- rbind(chart_df, data.frame(parameter = "Main Effect", ROI = roi, modality = metric, coefficient = beta, fdr_val = fdr))

      beta <- as.numeric(get(paste0(metric, "_results"))[which(get(paste0(metric, "_results"))$ROI == roi), "beta sex1:logWHIIRS"])
      fdr <- as.numeric(get(paste0(metric, "_results"))[which(get(paste0(metric, "_results"))$ROI == roi), "fdr_sig sex1:logWHIIRS"])
      
      if (metric == "AxD" | metric == "MD" | metric == "RD"){ # this is to make the trend about the amount of myelin, NOT about the raw values
        beta = -beta
      }
      
      # Store results
      chart_df <- rbind(chart_df, data.frame(parameter = "Sex Interaction", ROI = roi, modality = metric, coefficient = beta, fdr_val = fdr))
      
      
      beta <- as.numeric(get(paste0(metric, "_results"))[which(get(paste0(metric, "_results"))$ROI == roi), "beta female logWHIIRS"])
      fdr <- as.numeric(get(paste0(metric, "_results"))[which(get(paste0(metric, "_results"))$ROI == roi), "fdr_sig female logWHIIRS"])
      
      if (metric == "AxD" | metric == "MD" | metric == "RD"){ # this is to make the trend about the amount of myelin, NOT about the raw values
        beta = -beta
      }
      
      # Store results
      chart_df <- rbind(chart_df, data.frame(parameter = "Female", ROI = roi, modality = metric, coefficient = beta, fdr_val = fdr))
      
      
      
      beta <- as.numeric(get(paste0(metric, "_results"))[which(get(paste0(metric, "_results"))$ROI == roi), "beta male logWHIIRS"])
      fdr <- as.numeric(get(paste0(metric, "_results"))[which(get(paste0(metric, "_results"))$ROI == roi), "fdr_sig male logWHIIRS"])
      
      if (metric == "AxD" | metric == "MD" | metric == "RD"){ # this is to make the trend about the amount of myelin, NOT about the raw values
        beta = -beta
      }
      
      # Store results
      chart_df <- rbind(chart_df, data.frame(parameter = "Male", ROI = roi, modality = metric, coefficient = beta, fdr_val = fdr))
  }
}
```



%%%%%%%%%%%%%
Make heatmap
%%%%%%%%%%%%%

Making heatmap -- main effect and sex int.
```{r}
heatmap <- chart_df %>%
  filter(parameter %in% c("Main Effect", "Sex Interaction")) %>%  
  mutate(
    ROI = ifelse(str_detect(ROI, "^[A-Z0-9_]+$"), ROI, str_to_title(ROI)), # capitalizes the ROI values
    modality = factor(modality, levels = c("MWF", "R1", "R2", "FA", "AxD", "MD", "RD")),  # Custom order for modalities
    parameter = factor(parameter, levels = c("Main Effect", "Sex Interaction")),  # Set custom order
    star = case_when(
      fdr_val <= 0.0001 ~ "****",
      fdr_val <= 0.001 ~ "***",
      fdr_val <= 0.01 ~ "* *",
      fdr_val <= 0.05 ~ "*",
      TRUE ~ ""  # not significant
    )
  )

# Plot the heatmap with borders
g <- ggplot(heatmap, aes(x = parameter, y = ROI, fill = coefficient)) +
  ggtitle("log(WHIIRS) Significance") + 
  geom_tile(color = "white", linewidth = 0.1) +  # Add borders to each tile
  geom_text(aes(label = star), color = "black", size = 5, hjust = 0.5, vjust = 0.5, nudge_y = -.27) +  # Center text
  scale_fill_gradientn(
    colors = c("#4575B4", "#91BFDB", "#E0F3F8", "#FEE090", "#FC8D59", "#D73027"),
    limits = c(-0.4, 0.4),   # uniform across most heatmaps
    name = "B coefficient"
  ) + 

  facet_wrap(facets = ~modality, nrow = 1) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major = element_blank(),  # Remove major gridlines
        panel.grid.minor = element_blank(),  # Remove minor gridlines
        axis.ticks = element_blank(),        # Remove axis ticks
        panel.spacing = unit(0.03, "lines"))  # Reduce space between facets)  

print(g)

```



Making  heatmap -- female and male
```{r}
heatmap <- chart_df %>%
  filter(parameter %in% c("Female", "Male")) %>%  
  mutate(
    ROI = ifelse(str_detect(ROI, "^[A-Z0-9_]+$"), ROI, str_to_title(ROI)), # capitalizes the ROI values
    modality = factor(modality, levels = c("MWF", "R1", "R2", "FA", "AxD", "MD", "RD")),  # Custom order for modalities
    parameter = factor(parameter, levels = c("Female", "Male")),  # Set custom order
    star = case_when(
      fdr_val <= 0.0001 ~ "****",
      fdr_val <= 0.001 ~ "***",
      fdr_val <= 0.01 ~ "* *",
      fdr_val <= 0.05 ~ "*",
      TRUE ~ ""  # not significant
    )
  )

# Plot the heatmap with borders
g <- ggplot(heatmap, aes(x = parameter, y = ROI, fill = coefficient)) +
  ggtitle("log(WHIIRS) Significance") + 
  geom_tile(color = "white", linewidth = 0.1) +  # Add borders to each tile
  geom_text(aes(label = star), color = "black", size = 5, hjust = 0.5, vjust = 0.5, nudge_y = -.27) +  # Center text
  scale_fill_gradientn(
   colors = c("#4575B4", "#91BFDB", "#E0F3F8", "#FEE090", "#FC8D59", "#D73027"),
    limits = c(-0.4, 0.4),   # uniform across most heatmaps
    name = "B coefficient"
  ) + 

  facet_wrap(facets = ~modality, nrow = 1) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major = element_blank(),  # Remove major gridlines
        panel.grid.minor = element_blank(),  # Remove minor gridlines
        axis.ticks = element_blank(),        # Remove axis ticks
        panel.spacing = unit(0.03, "lines"))  # Reduce space between facets)  

print(g)

```



